name: 'Get version bump'
description: 'Determine which version (major.minor.patch) to bump based on the PR body or provided input'

inputs:
  text:
    description: 'Optional text to use instead of the default PR body'
    required: false
    default: '${{ github.event.pull_request.body }}'

outputs:
  bump:
    description: 'Which version to bump (major, minor, patch or none)'
    value: '${{ steps.get-bump.outputs.bump }}'

runs:
  using: 'node12'
  main: 'index.js'